# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, lib, buildGoPackage, fetchgit }:

buildGoPackage rec {
  pname = "cgd";
  version = "2012-09-18";
  rev = "c08b219280fb87f64df7aa356300efefca528401";

  goPackagePath = "github.com/uriel/cgd";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/uriel/cgd";
    sha256 = "1qa9phkx1z9vyb8f9jv2r8q89alwxyask6d0f2g51rlixl9n5qpx";
  };

  meta = {
  	description = "A daemon that can serve a CGI script over HTTP or FastCGI";
  	homepage = "http://repo.cat-v.org/cgd/";
  	license = lib.licenses.publicDomain;
  };
}
