# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, lib, buildGoPackage, fetchgit }:

buildGoPackage rec {
  pname = "cgd";
  version = "2021-07-26";
  rev = "53c82b60590f292fdff27adb59dbf960fb95c66e";
  preBuild = ''
    export CGO_ENABLED=0
  '';
  goPackagePath = "github.com/ylh/cgd";

  src = fetchgit {
    inherit rev;
    url = "https://${goPackagePath}";
    sha256 = "15652pxa2ii95mz7bbnfcby7s896xp20rb23i7k2mnr2k9rhkysg";
  };

  meta = {
  	description = "A daemon that can serve a CGI script over HTTP or FastCGI";
  	homepage = "http://repo.cat-v.org/cgd/";
  	license = lib.licenses.publicDomain;
  };
}
